{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'ivanovvisheslav@mail.ru', 'password': '5lkFUGQ1CF'}", "status": "passed", "start": 1760500587048, "stop": 1760500587503}], "parameters": [{"name": "test_case_id", "value": "2"}], "start": 1760500587048, "stop": 1760500587507, "uuid": "8b55776d-6f63-417f-9e78-47177146ddf8", "historyId": "a2ddabbcc0cbb5f6cee07081069caa8f", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "19784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}