{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'jakub1983@mail.ru', 'password': 'qXJ9wrlqd0'}", "status": "passed", "start": 1760500584786, "stop": 1760500585209}], "parameters": [{"name": "test_case_id", "value": "1"}], "start": 1760500584786, "stop": 1760500585210, "uuid": "5a7c9e2d-4af5-4081-acb6-11be94613ac1", "historyId": "718055d33a25ba946c8e26ade583342a", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "19784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}